name: Deploy
 
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-20.04
        timeout-minutes: 30
        steps:
            -   run: ls -la
            -   uses: actions/checkout@master
            -   run: sudo apt update && sudo apt upgrade

            -   run: sudo apt-get install rsync
            
            -   name: Deploy mockup pages on server
                id: deploy_mockup
                uses: Pendect/action-rsyncer@v2.0.0
                env:
                    DEPLOY_KEY: ${{secrets.ID_RSA}}
                with:
                    flags: '-avc --delete'
                    options: ''
                    ssh_options: ''
                    src: '.'
                    dest: 'root@"${{vars.MOCKUP_SERVER_IP}}":/var/www/html'
 
            -   name: Display status from deploy
                run: echo "${{ steps.deploy.outputs.status }}"
